# cf https://github.com/marketplace/actions/release-drafter
name-template: 'v$RESOLVED_VERSION 🧪'
tag-template: 'v$RESOLVED_VERSION'
prerelease: true
prerelease-identifier: rc
categories:
  - type: version-resolver
    semver-increment: major
    when:
      labels:
        - major
  - type: version-resolver
    semver-increment: minor
    when:
      labels:
        - minor
  - type: version-resolver
    semver-increment: patch
    when:
      labels:
        - patch
  - type: version-resolver
    semver-increment: patch
  - type: pre-exclude
    when:
      labels:
        - ignore-for-release
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
template: |
  ## Changes

  $CHANGES
