# cf https://github.com/marketplace/actions/release-drafter
name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch
exclude-labels:
  - ignore-for-release
autolabeler:
  - label: major
    title:
      - '/^[a-z]+(\(.+\))?!:/'
  - label: minor
    title:
      - '/^feat(\(.+\))?:/'
  - label: patch
    title:
      - '/^(fix|perf)(\(.+\))?:/'
  - label: ignore-for-release
    title:
      - '/^(refactor|chore|docs|ci|test)(\(.+\))?:/'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
template: |
  ## Changes

  $CHANGES
