# cf https://github.com/marketplace/actions/release-drafter
name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: "💥 Breaking Changes"
    semver-increment: major
    when:
      labels:
        - major
  - title: "🚀 Features"
    semver-increment: minor
    when:
      labels:
        - minor
  - title: "🐛 Bug Fixes & Improvements"
    semver-increment: patch
    when:
      labels:
        - patch
  - type: version-resolver
    semver-increment: patch
  - type: pre-exclude
    when:
      labels:
        - ignore-for-release
autolabeler:
  - label: major
    title:
      - '/^[a-z]+(\(.+\))?!:/'
  - label: minor
    title:
      - '/^feat(\(.+\))?:/'
  - label: patch
    title:
      - '/^(fix|perf)(\(.+\))?:/'
  - label: ignore-for-release
    title:
      - '/^(ci|test)(\(.+\))?:/'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
template: |
  ## Changes

  $CHANGES
