export { DynamoDBSingleTableSnapshotStorageAdapter } from './singleTableAdapter';
export {
  SNAPSHOT_TABLE_PK,
  SNAPSHOT_TABLE_SK,
  SNAPSHOT_TABLE_AGGREGATE_KEY,
  SNAPSHOT_TABLE_AGGREGATE_VERSION_KEY,
  SNAPSHOT_TABLE_REDUCER_VERSION_KEY,
  SNAPSHOT_TABLE_EVENT_STORE_ID_KEY,
  SNAPSHOT_TABLE_SAVED_AT_KEY,
  SNAPSHOT_TABLE_GSI_PK_KEY,
  SNAPSHOT_TABLE_GSI_SK_KEY,
  SNAPSHOT_TABLE_BY_REDUCER_VERSION_INDEX_NAME,
} from './constants';
