name: Install Node Dependencies
description: Install dependencies using pnpm
runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Sync node_modules cache
      id: sync-node-modules-cache
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('.nvmrc') }}-${{ hashFiles('./pnpm-lock.yaml') }}

    - name: Install node_modules
      run: if [ '${{ steps.sync-node-modules-cache.outputs.cache-hit }}' != 'true' ]; then pnpm install --frozen-lockfile; fi
      shell: bash
