name: 📝 Draft or update next release
concurrency: draft_or_update_next_release

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  CI: true

jobs:
  draft-stable-release:
    name: 📝 Draft or update next stable release
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6

      - uses: release-drafter/release-drafter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  draft-prerelease:
    name: 📝 Draft or update next pre-release
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6

      - uses: release-drafter/release-drafter@v7
        with:
          config-name: release-drafter-prerelease.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
